import { prisma } from "../../config/database";
const PDFDocument = require("pdfkit");
import fs from "fs";
import path from "path";

const kopSuratPath = path.join(__dirname, "../../../assets/KOP SURAT.png");

// Helper to generate PDF with header
const generatePDF = (
  title: string,
  data: any[],
  columns: string[]
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 48, bottom: 48, left: 48, right: 48 },
      // IMPORTANT: avoid phantom pages caused by buffered page switching
      bufferPages: false,
    });

    const buffers: Buffer[] = [];
    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    // ---- Style constants ----
    const fontRegular = "Helvetica";
    const fontBold = "Helvetica-Bold";

    const headerBg = "#f2f2f2";
    const borderColor = "#bdbdbd";
    const textColor = "#111111";

    const titleFontSize = 17;
    const metaFontSize = 10;
    const tableHeaderFontSize = 10;
    const tableBodyFontSize = 9.5;

    const cellPaddingX = 6;
    const cellPaddingY = 4;
    const rowGap = 0; // keep tight, borders give separation

    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const marginLeft = doc.page.margins.left;
    const marginRight = doc.page.margins.right;
    const marginTop = doc.page.margins.top;
    const marginBottom = doc.page.margins.bottom;

    const contentWidth = pageWidth - marginLeft - marginRight;

    const totalColumns = Math.max(columns.length, 1);
    const colWidth = contentWidth / totalColumns;

    const isNumeric = (v: unknown) =>
      typeof v === "number" ||
      (typeof v === "string" && /^-?\d+(\.\d+)?$/.test(v.trim()));

    const toCellText = (v: any) => {
      if (v === null || v === undefined) return "";
      if (typeof v === "object") return JSON.stringify(v);
      return String(v);
    };

    // Convert backend keys like totalStockOut / stock_out / stockOut -> "Total Stock Out"
    const toHeaderLabel = (key: string) => {
      const spaced = key
        .replace(/[_-]+/g, " ")
        .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
        .trim();
      return spaced
        .split(/\s+/)
        .filter(Boolean)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");
    };

    const getRowHeight = (row: any, fontSize: number) => {
      const heights = columns.map(col => {
        const text = toCellText(row?.[col]);
        const w = Math.max(colWidth - cellPaddingX * 2, 10);
        const h = doc.heightOfString(text, {
          width: w,
          align: "left",
        });
        return h + cellPaddingY * 2;
      });
      const maxH = Math.max(...heights, fontSize + cellPaddingY * 2);
      return Math.ceil(maxH);
    };

    // One-pass footer (no buffered page switching)
    let currentPageNumber = 1;
    const drawFooter = (reportName: string, pageNumber: number) => {
      const footerY = doc.page.height - doc.page.margins.bottom + 18;

      doc
        .font(fontRegular)
        .fontSize(9)
        .fillColor("#666666")
        .text(reportName, marginLeft, footerY, {
          width: contentWidth,
          align: "left",
        });

      doc
        .font(fontRegular)
        .fontSize(8.5)
        .fillColor("#999999")
        .text(
          "Generated by RAYA IMS (Inventory Management System)",
          marginLeft,
          footerY,
          {
            width: contentWidth,
            align: "center",
          }
        );

      // Without bufferPages we cannot know total pages upfront reliably.
      // Keep it as "Page X" to avoid adding blank pages.
      doc
        .font(fontRegular)
        .fontSize(9)
        .fillColor("#666666")
        .text(`Page ${pageNumber}`, marginLeft, footerY, {
          width: contentWidth,
          align: "right",
        });
    };

    // Reserve a small area so table rows never push content into the footer zone.
    const footerReserveHeight = 26;

    let tableY = doc.y;

    const checkPageBreak = (requiredHeight: number) => {
      const bottomLimit =
        doc.page.height - doc.page.margins.bottom - footerReserveHeight;
      if (tableY + requiredHeight > bottomLimit) {
        // finalize footer on the current page
        drawFooter(title, currentPageNumber);

        doc.addPage();
        currentPageNumber += 1;

        tableY = doc.page.margins.top;
        doc.y = tableY;
        drawTableHeader();
      }
    };

    const drawTableHeader = () => {
      doc.save();

      const headerHeight = Math.max(tableHeaderFontSize + cellPaddingY * 2, 20);

      // background band
      doc
        .fillColor(headerBg)
        .rect(marginLeft, tableY, contentWidth, headerHeight)
        .fill();

      // border
      doc
        .lineWidth(0.75)
        .strokeColor(borderColor)
        .rect(marginLeft, tableY, contentWidth, headerHeight)
        .stroke();

      // vertical borders + text
      doc.font(fontBold).fontSize(tableHeaderFontSize).fillColor(textColor);

      for (let i = 0; i < totalColumns; i++) {
        const x = marginLeft + i * colWidth;
        if (i > 0) {
          doc
            .lineWidth(0.5)
            .strokeColor(borderColor)
            .moveTo(x, tableY)
            .lineTo(x, tableY + headerHeight)
            .stroke();
        }

        const colKey = columns[i] ?? "";
        const label = toHeaderLabel(String(colKey));

        doc.text(label, x + cellPaddingX, tableY + cellPaddingY, {
          width: colWidth - cellPaddingX * 2,
          align: "center",
          lineBreak: false,
          ellipsis: true,
        });
      }

      doc.restore();

      tableY += headerHeight + rowGap;
      doc.y = tableY;
    };

    const drawTableRow = (row: any) => {
      doc.font(fontRegular).fontSize(tableBodyFontSize).fillColor(textColor);

      const rowHeight = getRowHeight(row, tableBodyFontSize);
      checkPageBreak(rowHeight);

      // row border
      doc
        .lineWidth(0.5)
        .strokeColor(borderColor)
        .rect(marginLeft, tableY, contentWidth, rowHeight)
        .stroke();

      for (let i = 0; i < totalColumns; i++) {
        const x = marginLeft + i * colWidth;
        if (i > 0) {
          doc
            .lineWidth(0.5)
            .strokeColor(borderColor)
            .moveTo(x, tableY)
            .lineTo(x, tableY + rowHeight)
            .stroke();
        }

        const key = columns[i];
        const raw = row?.[key];
        const text = toCellText(raw);

        const align = isNumeric(raw) ? "right" : "left";

        doc.text(text, x + cellPaddingX, tableY + cellPaddingY, {
          width: colWidth - cellPaddingX * 2,
          align,
        });
      }

      tableY += rowHeight + rowGap;
      doc.y = tableY;
    };

    // ---- Header (kop surat) page 1 only ----
    let y = marginTop;

    // Manual kop surat (text-based) to avoid image sizing/layout issues
    // (no business logic / data changes)
    doc
      .font(fontBold)
      .fontSize(14)
      .fillColor("#0b7a3b")
      .text("PT. RAYA MAKMUR AIR CARGO SERVICE", marginLeft, y, {
        width: contentWidth,
        align: "center",
      });

    y = doc.y + 2;

    doc
      .font(fontBold)
      .fontSize(11)
      .fillColor("#0b7a3b")
      .text("Domestic Air Freight Forwarder", marginLeft, y, {
        width: contentWidth,
        align: "center",
      });

    y = doc.y + 6;

    doc
      .font(fontRegular)
      .fontSize(9)
      .fillColor("#333333")
      .text(
        "Office: Soewarna Business Park, Lot 2A Soekarno Hatta International Airport",
        marginLeft,
        y,
        { width: contentWidth, align: "center" }
      );

    y = doc.y + 2;

    doc
      .font(fontRegular)
      .fontSize(9)
      .fillColor("#333333")
      .text("Kota Tangerang - Banten", marginLeft, y, {
        width: contentWidth,
        align: "center",
      });

    y = doc.y + 2;

    doc
      .font(fontRegular)
      .fontSize(9)
      .fillColor("#333333")
      .text(
        "Telp.: 0813 8536 5667   |   E-mail: rully_meitin@yahoo.com",
        marginLeft,
        y,
        {
          width: contentWidth,
          align: "center",
        }
      );

    y = doc.y + 8;

    // separator line
    doc
      .lineWidth(1)
      .strokeColor("#0b7a3b")
      .moveTo(marginLeft, y)
      .lineTo(marginLeft + contentWidth, y)
      .stroke();

    y += 10;

    // Title
    doc
      .font(fontBold)
      .fontSize(titleFontSize)
      .fillColor(textColor)
      .text(title, marginLeft, y, {
        width: contentWidth,
        align: "center",
      });

    y = doc.y + 6;

    // Generated date (right)
    doc
      .font(fontRegular)
      .fontSize(metaFontSize)
      .fillColor("#444444")
      .text(`Generated on: ${new Date().toLocaleDateString()}`, marginLeft, y, {
        width: contentWidth,
        align: "right",
      });

    y = doc.y + 14;

    // ---- Table ----
    tableY = y;
    doc.y = tableY;

    drawTableHeader();

    data.forEach(row => {
      drawTableRow(row);
    });

    // Footer with total page count
    drawFooter(title, currentPageNumber);

    doc.end();
  });
};

export const getStockReport = async () => {
  const items = await prisma.item.findMany({
    include: {
      brand: true,
      category: true,
      stockIns: true,
      stockOuts: true,
      loans: true,
    },
  });

  return items.map(item => ({
    id: item.id,
    name: item.name,
    code: item.itemCode,
    brand: item.brand?.name || "",
    category: item.category?.name || "",
    totalStockIn: item.stockIns.reduce((sum: number, si) => sum + si.qty, 0),
    totalStockOut: item.stockOuts.reduce((sum: number, so) => sum + so.qty, 0),
    totalLoans: item.loans
      .filter(l => l.status !== "RETURNED")
      .reduce((sum: number, l) => sum + l.qty, 0),
  }));
};

export const getStockReportPDF = async () => {
  const data = await getStockReport();
  const columns = [
    "name",
    "code",
    "brand",
    "category",
    "totalStockIn",
    "totalStockOut",
    "totalLoans",
  ];
  return generatePDF("Stock Report", data, columns);
};

export const getTransactionReport = async (
  startDate?: string,
  endDate?: string
) => {
  const whereStockIn: any = {};
  const whereStockOut: any = {};

  if (startDate && endDate) {
    whereStockIn.date = { gte: new Date(startDate), lte: new Date(endDate) };
    whereStockOut.date = { gte: new Date(startDate), lte: new Date(endDate) };
  }

  const stockIns = await prisma.stockIn.findMany({
    where: whereStockIn,
    include: { item: true, supplier: true },
  });

  const stockOuts = await prisma.stockOut.findMany({
    where: whereStockOut,
    include: { item: true },
  });

  return {
    stockIns: stockIns.map(si => ({
      type: "Stock In",
      item: si.item.name,
      qty: si.qty,
      supplier: si.supplier?.name || "",
      date: si.date.toISOString().split("T")[0],
    })),
    stockOuts: stockOuts.map(so => ({
      type: "Stock Out",
      item: so.item.name,
      qty: so.qty,
      reason: so.reason || "",
      date: so.date.toISOString().split("T")[0],
    })),
  };
};

export const getTransactionReportPDF = async (
  startDate?: string,
  endDate?: string
) => {
  const data = await getTransactionReport(startDate, endDate);
  const allData = [...data.stockIns, ...data.stockOuts];
  const columns = ["type", "item", "qty", "supplier", "reason", "date"];
  return generatePDF("Transaction Report", allData, columns);
};

export const getLoanReport = async (status?: string) => {
  const where: any = {};
  if (status) where.status = status;

  const loans = await prisma.loan.findMany({
    where,
    include: { item: true, user: true },
  });

  return loans.map(loan => ({
    id: loan.id,
    item: loan.item.name,
    borrower: loan.user.name,
    qty: loan.qty,
    status: loan.status,
    loanDate: loan.startDate?.toISOString().split("T")[0] || "",
    returnDate: loan.endDate?.toISOString().split("T")[0] || "",
    overdue: loan.endDate && new Date() > loan.endDate ? "Yes" : "No",
  }));
};

export const getLoanReportPDF = async (status?: string) => {
  const data = await getLoanReport(status);
  const columns = [
    "item",
    "borrower",
    "qty",
    "status",
    "loanDate",
    "returnDate",
    "overdue",
  ];
  return generatePDF("Loan Report", data, columns);
};

export const getSupplierReport = async () => {
  const suppliers = await prisma.supplier.findMany({
    include: { stockIns: { include: { item: true } } },
  });

  return suppliers.map(sup => ({
    name: sup.name,
    totalTransactions: sup.stockIns.length,
    totalQty: sup.stockIns.reduce((sum: number, si) => sum + si.qty, 0),
    lastTransaction:
      sup.stockIns.length > 0
        ? sup.stockIns[sup.stockIns.length - 1].date.toISOString().split("T")[0]
        : "",
  }));
};

export const getSupplierReportPDF = async () => {
  const data = await getSupplierReport();
  const columns = ["name", "totalTransactions", "totalQty", "lastTransaction"];
  return generatePDF("Supplier Report", data, columns);
};

export const getSummary = async () => {
  const totalItems = await prisma.item.count();
  const totalSuppliers = await prisma.supplier.count();
  const totalStockIn = await prisma.stockIn.count();
  const totalStockOut = await prisma.stockOut.count();
  const totalLoans = await prisma.loan.count();
  const totalUsers = await prisma.user.count({ where: { isActive: true } });

  return {
    totalItems,
    totalSuppliers,
    totalStockIn,
    totalStockOut,
    totalLoans,
    totalUsers,
  };
};

export const getSummaryPDF = async () => {
  const data = [await getSummary()];
  const columns = [
    "totalItems",
    "totalSuppliers",
    "totalStockIn",
    "totalStockOut",
    "totalLoans",
    "totalUsers",
  ];
  return generatePDF("Summary Report", data, columns);
};

export const getUserActivityReport = async () => {
  // Simple activity based on counts per role
  const users = await prisma.user.findMany({
    where: { isActive: true },
    include: { loans: true },
  });

  return users.map(user => ({
    name: user.name,
    role: user.role,
    totalLoans: user.loans.length,
  }));
};

export const getUserActivityReportPDF = async () => {
  const data = await getUserActivityReport();
  const columns = ["name", "role", "totalLoans"];
  return generatePDF("User Activity Report", data, columns);
};
